package co.tucompra.antifraude.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ip implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Ip() {
    }

}