package co.tucompra.antifraude.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Respuesta implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Respuesta() {
    }
    
    String mensaje;
	Integer score;
	
	public Respuesta(String mensaje, Integer score) {
		super();
		this.mensaje = mensaje;
		this.score = score;
	}
	public String getMensaje() {
		return mensaje;
	}
	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}
	public Integer getScore() {
		return score;
	}
	public void setScore(Integer score) {
		this.score = score;
	}
	@Override
	public String toString() {
		return "Respuesta [mensaje=" + mensaje + ", score=" + score + "]";
	}

}