package co.tucompra.antifraude.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TarjetaDeCredito implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TarjetaDeCredito() {
    }
    
    String numeroTarjeta;
	Integer cantidadIntentos;
	Integer cantidadIntentosRegla;
	String configuracionRegla;
	String paisEmisorTarjeta;
	String validarPais;
	String mensaje;
	Integer score;
	Integer nivel;
	boolean validarCantidadIntentos;
	Double valorAcumulado;
	Double valorMaximoAcumuladoRegla;
	boolean validarMaximoAcumulado;
	boolean existeTarjetaCifin;
	
	public String getNumeroTarjeta() {
		return numeroTarjeta;
	}
	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}
	public Integer getCantidadIntentos() {
		return cantidadIntentos;
	}
	public void setCantidadIntentos(Integer cantidadIntentos) {
		this.cantidadIntentos = cantidadIntentos;
	}
	public String getConfiguracionRegla() {
		return configuracionRegla;
	}
	public void setConfiguracionRegla(String configuracionRegla) {
		this.configuracionRegla = configuracionRegla;
	}
	public String getMensaje() {
		return mensaje;
	}
	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}
	
	public String getValidarPais() {
		try {
			
			if(paisEmisorTarjeta==null||paisEmisorTarjeta.equals("")){
				validarPais="false";
				return validarPais;
			}
			
			if(configuracionRegla.toLowerCase().contains(paisEmisorTarjeta.toLowerCase())){
				validarPais="true";
			}else{
				validarPais="false";
			}
		} catch (Exception e) {
		}
		return validarPais;
	}
	
	public void setValidarPais(String validarPais) {
		this.validarPais = validarPais;
	}
	
	public String getPaisEmisorTarjeta() {
		return paisEmisorTarjeta;
	}
	public void setPaisEmisorTarjeta(String paisEmisorTarjeta) {
		this.paisEmisorTarjeta = paisEmisorTarjeta;
	}
	public Integer getCantidadIntentosRegla() {
		return cantidadIntentosRegla;
	}
	public void setCantidadIntentosRegla(Integer cantidadIntentosRegla) {
		this.cantidadIntentosRegla = cantidadIntentosRegla;
	}
	public Integer getScore() {
		return score;
	}
	public void setScore(Integer score) {
		this.score = score;
	}
	public Integer getNivel() {
		return nivel;
	}
	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
	public boolean isValidarCantidadIntentos() {

		if(cantidadIntentos!=null&&cantidadIntentosRegla!=null){
			if(cantidadIntentos<cantidadIntentosRegla){
				validarCantidadIntentos=true;
			}else{
				validarCantidadIntentos=false;
			}
		}
		
		return validarCantidadIntentos;
	}
	public void setValidarCantidadIntentos(boolean validarCantidadIntentos) {
		this.validarCantidadIntentos = validarCantidadIntentos;
	}
	public Double getValorAcumulado() {
		return valorAcumulado;
	}
	public void setValorAcumulado(Double valorAcumulado) {
		this.valorAcumulado = valorAcumulado;
	}
	public Double getValorMaximoAcumuladoRegla() {
		return valorMaximoAcumuladoRegla;
	}
	public void setValorMaximoAcumuladoRegla(Double valorMaximoAcumuladoRegla) {
		this.valorMaximoAcumuladoRegla = valorMaximoAcumuladoRegla;
	}
	public boolean isValidarMaximoAcumulado() {
		if(valorAcumulado!=null&&valorMaximoAcumuladoRegla!=null){
			if(valorAcumulado<valorMaximoAcumuladoRegla){
				validarMaximoAcumulado=true;
			}else{
				validarMaximoAcumulado=false;
			}
		}
		return validarMaximoAcumulado;
	}
	public void setValidarMaximoAcumulado(boolean validarMaximoAcumulado) {
		this.validarMaximoAcumulado = validarMaximoAcumulado;
	}
	public boolean isExisteTarjetaCifin() {
		return existeTarjetaCifin;
	}
	public void setExisteTarjetaCifin(boolean existeTarjetaCifin) {
		this.existeTarjetaCifin = existeTarjetaCifin;
	}

}