package co.tucompra.antifraude.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaccion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Transaccion() {
    }
    
    private Double valorTransaccion;
	private Double valorMaximo;
	private Double valorMinimo;
	private String mensaje;
	private Integer nivel;
	private Integer score;
	private boolean estaEnRango;
	
	public Double getValorTransaccion() {
		return valorTransaccion;
	}
	public void setValorTransaccion(Double valorTransaccion) {
		this.valorTransaccion = valorTransaccion;
	}
	public Double getValorMaximo() {
		return valorMaximo;
	}
	public void setValorMaximo(Double valorMaximo) {
		this.valorMaximo = valorMaximo;
	}
	public Double getValorMinimo() {
		return valorMinimo;
	}
	public void setValorMinimo(Double valorMinimo) {
		this.valorMinimo = valorMinimo;
	}
	public String getMensaje() {
		return mensaje;
	}
	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}
	public Integer getNivel() {
		return nivel;
	}
	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
	public Integer getScore() {
		return score;
	}
	public void setScore(Integer score) {
		this.score = score;
	}
	public boolean isEstaEnRango() {
		if(valorTransaccion!=null && valorMaximo!=null && valorMinimo!=null){
			if(valorTransaccion<=valorMaximo && valorTransaccion>=valorMinimo){
				estaEnRango=true;
			}else{
				estaEnRango=false;
			}
		}
		return estaEnRango;
	}
	public void setEstaEnRango(boolean estaEnRango) {
		this.estaEnRango = estaEnRango;
	}

}